SELECT
  y.doi,
  y.title,
  y.issued,
  y.issued_year,
  y.container_title,
  y.publisher,
  y.member,
  EXTRACT(DATE FROM TIMESTAMP_MILLIS(y.created)) AS created,
  y.published_print,
  y.published_online,
  y.issn,
  y.page,
  y.license,
  y.link,
  y.reference_count,
  y.is_referenced_by_count,
  EXTRACT(DATE FROM TIMESTAMP_MILLIS(y.indexed)) AS indexed
FROM (
  SELECT
    doi,
    title,
    COALESCE(SAFE.PARSE_DATE('%Y-%m',
        issued),
      SAFE.PARSE_DATE('%Y-%m-%d',
        issued),
      SAFE.PARSE_DATE('%Y',
        issued)) AS issued,
    issued_year,
    container_title,
    publisher,
    member,
    created,
    COALESCE(SAFE.PARSE_DATE('%Y-%m',
        published_print),
      SAFE.PARSE_DATE('%Y-%m-%d',
        published_print),
      SAFE.PARSE_DATE('%Y',
        published_print)) AS published_print,
    COALESCE(SAFE.PARSE_DATE('%Y-%m',
        published_online),
      SAFE.PARSE_DATE('%Y-%m-%d',
        published_online),
      SAFE.PARSE_DATE('%Y',
        published_online)) AS published_online,
    issn,
    page,
    license,
    link,
    reference_count,
    is_referenced_by_count,
    indexed
  FROM
    `api-project-764811344545.cr_dump.cr_jan21`) AS y
