SELECT publisher,
       title,
       abstract,
       reference_count,
       is_referenced_by_count,
       doi,
       member,
       created,
       deposited,
       indexed,
       issued,
       posted,
       accepted,
       container_title,
       issue,
       volume,
       page,
       article_number,
       published_print,
       published_online,
       issn,
       archive,
       license,
       funder,
       link,
       relation
FROM (
     SELECT publisher,
            title[SAFE_OFFSET(0)] as title,
            abstract,
            reference_count,
            is_referenced_by_count,
            y.doi,
            member,
            EXTRACT(DATE FROM TIMESTAMP_MILLIS(created.timestamp)) AS created,
            EXTRACT(DATE FROM TIMESTAMP_MILLIS(deposited.timestamp)) AS deposited,
            EXTRACT(DATE FROM TIMESTAMP_MILLIS(indexed.timestamp)) AS indexed,
            DATE(CONCAT(CAST(issued.date_parts[SAFE_OFFSET(0)] AS STRING), "-",
                 COALESCE(CAST(issued.date_parts[SAFE_OFFSET(1)] AS STRING), "1"), "-",
                 COALESCE(CAST(issued.date_parts[SAFE_OFFSET(2)] AS STRING), "1"))) AS issued,
            DATE(CONCAT(CAST(posted.date_parts[SAFE_OFFSET(0)] AS STRING), "-",
                 COALESCE(CAST(posted.date_parts[SAFE_OFFSET(1)] AS STRING), "1"), "-",
                 COALESCE(CAST(posted.date_parts[SAFE_OFFSET(2)] AS STRING), "1"))) AS posted,
            DATE(CONCAT(CAST(accepted.date_parts[SAFE_OFFSET(0)] AS STRING), "-",
                 COALESCE(CAST(accepted.date_parts[SAFE_OFFSET(1)] AS STRING), "1"), "-",
                 COALESCE(CAST(accepted.date_parts[SAFE_OFFSET(2)] AS STRING), "1"))) AS accepted,
            container_title[SAFE_OFFSET(0)] AS container_title,
            y.issue,
            y.volume,
            page,
            article_number,
            DATE(CONCAT(CAST(published_print.date_parts[SAFE_OFFSET(0)] AS STRING), "-",
                 COALESCE(CAST(published_print.date_parts[SAFE_OFFSET(1)] AS STRING), "1"), "-",
                 COALESCE(CAST(published_print.date_parts[SAFE_OFFSET(2)] AS STRING), "1"))) AS published_print,
            DATE(CONCAT(CAST(published_online.date_parts[SAFE_OFFSET(0)] AS STRING), "-",
                 COALESCE(CAST(published_online.date_parts[SAFE_OFFSET(1)] AS STRING), "1"), "-",
                 COALESCE(CAST(published_online.date_parts[SAFE_OFFSET(2)] AS STRING), "1"))) AS published_online,
            STRING_AGG(DISTINCT(issn)) AS issn,
            STRING_AGG(DISTINCT(archive)) AS archive,
            ARRAY_AGG(STRUCT(EXTRACT(DATE FROM TIMESTAMP_MILLIS(lic.start.timestamp)) AS start,
                             lic.url,
                             lic.delay_in_days,
                             lic.content_version)) AS license,
            ARRAY_AGG(STRUCT(fun.name,
                      fun.doi,
                      fun.award,
                      fun.doi_asserted_by)) AS funder,
            ARRAY_AGG(STRUCT(lin.url,
                      lin.content_type,
                      lin.content_version,
                      lin.intended_application)) AS link,
            ANY_VALUE(relation) AS relation,
            type
     FROM `api-project-764811344545.cr_instant.cr_feb21_complete` AS y
     LEFT JOIN UNNEST(issn) AS issn
     LEFT JOIN UNNEST(archive) AS archive
     LEFT JOIN UNNEST(license) AS lic
     LEFT JOIN UNNEST(funder) AS fun
     LEFT JOIN UNNEST(link) AS lin
     GROUP BY publisher,
              title,
              abstract,
              reference_count,
              is_referenced_by_count,
              doi,
              member,
              created,
              deposited,
              indexed,
              issued,
              posted,
              accepted,
              container_title,
              issue,
              volume,
              page,
              article_number,
              published_print,
              published_online,
              type
     HAVING type = "journal-article"
     )
WHERE issued >= "2013-01-01"
