SELECT publisher,
       title,
       abstract,
       reference_count,
       is_referenced_by_count,
       doi,
       member,
       created,
       deposited,
       indexed,
       DATE(CONCAT(issued_year, "-", COALESCE(issued_month, "1"), "-", COALESCE(issued_day, "1"))) AS issued,
       DATE(CONCAT(posted_year, "-", COALESCE(posted_month, "1"), "-", COALESCE(posted_day, "1"))) AS posted,
       DATE(CONCAT(accepted_year, "-", COALESCE(accepted_month, "1"), "-", COALESCE(accepted_day, "1"))) AS accepted,
       container_title,
       issue,
       volume,
       page,
       article_number,
       DATE(CONCAT(published_print_year, "-", COALESCE(published_print_month, "1"), "-", COALESCE(published_print_day, "1"))) AS published_print,
       DATE(CONCAT(published_online_year, "-", COALESCE(published_online_month, "1"), "-", COALESCE(published_online_day, "1"))) AS published_online,
FROM (
    SELECT publisher,
           title,
           abstract,
           reference_count,
           is_referenced_by_count,
           doi,
           member,
           EXTRACT(DATE FROM TIMESTAMP_MILLIS(created.timestamp)) AS created,
           EXTRACT(DATE FROM TIMESTAMP_MILLIS(deposited.timestamp)) AS deposited,
           EXTRACT(DATE FROM TIMESTAMP_MILLIS(indexed.timestamp)) AS indexed,
           CAST(issued.date_parts[SAFE_OFFSET(0)] AS STRING) AS issued_year,
           CAST(issued.date_parts[SAFE_OFFSET(1)] AS STRING) AS issued_month,
           CAST(issued.date_parts[SAFE_OFFSET(2)] AS STRING) AS issued_day,
           CAST(posted.date_parts[SAFE_OFFSET(0)] AS STRING) AS posted_year,
           CAST(posted.date_parts[SAFE_OFFSET(1)] AS STRING) AS posted_month,
           CAST(posted.date_parts[SAFE_OFFSET(2)] AS STRING) AS posted_day,
           CAST(accepted.date_parts[SAFE_OFFSET(0)] AS STRING) AS accepted_year,
           CAST(accepted.date_parts[SAFE_OFFSET(1)] AS STRING) AS accepted_month,
           CAST(accepted.date_parts[SAFE_OFFSET(2)] AS STRING) AS accepted_day,
           container_title,
           issue,
           volume,
           page,
           article_number,
           CAST(published_print.date_parts[SAFE_OFFSET(0)] AS STRING) AS published_print_year,
           CAST(published_print.date_parts[SAFE_OFFSET(1)] AS STRING) AS published_print_month,
           CAST(published_print.date_parts[SAFE_OFFSET(2)] AS STRING) AS published_print_day,
           CAST(published_online.date_parts[SAFE_OFFSET(0)] AS STRING) AS published_online_year,
           CAST(published_online.date_parts[SAFE_OFFSET(1)] AS STRING) AS published_online_month,
           CAST(published_online.date_parts[SAFE_OFFSET(2)] AS STRING) AS published_online_day,
    FROM `api-project-764811344545.cr_instant.cr_feb21_complete`
    WHERE doi IN ("10.7717/peerj.2323", "10.1016/j.suronc.2012.09.002"))
